// import { CormorantInfant } from 'next/font/google'
import { Cormorant_Infant } from 'next/font/google'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const cormorant = Cormorant_Infant({
  weight: ["400", "700"],
  subsets: ["cyrillic"],
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${cormorant.className}`}>
        {children}
      </body>
    </html>
  );
}
