services:

    json-server:
        build:
            context: ../json_server
            dockerfile: ../docker_config/dockerfile.backend
        ports:
            - "4000:4000"
        volumes:
            - ../json_server:/usr/app
        networks:
            - iviteWorks
    nextjs:
        build:
            context: ../inite-next-15-1
            dockerfile: ../docker_config/dockerfile.frontend
        ports:
            - "3000:3000"
        volumes:
            - ../inite-next-15-1:/usr/app
            - ../certs:/etc/letsencrypt # Директория для хранения сертификатов
        networks:
            - iviteWorks
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../certs:/etc/letsencrypt
        networks:
            - iviteWorks

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ../certs:/etc/letsencrypt # Та же директория, что и для Nginx
            - ../certs:/var/lib/letsencrypt # Для временных файлов
            - ../certs/logs:/var/log/letsencrypt # Для логов
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        networks:
            - iviteWorks

networks:
    iviteWorks:
