FROM node:22

WORKDIR /usr/app

COPY package*.json ./

RUN npm install -g npm@latest

# Установка зависимостей
RUN npm install --legacy-peer-deps

RUN npm ci 

COPY . .

RUN npm i yarn
CMD ["npm i yarn","&&""yarn", "run", "json-server", "data.json", "--port 4000"]
